### ISSUE TITLE
What is WS_SECRET

### ISSUE THREAD

**Issue by zaq1tomo** [cubedro/eth-net-intelligence-api#255]
I want to list my node on https://ethstats.net/, but I do not know WS_SECRET. 
I accessed the link at http://tinyurl.com/ofndjbo but could not enter the group.

**Comment by unixfox** [comment]
@StephanTual @cubedro Is it possible to have an updated link for the Skype group because I want to list my node on ethstats?

**Comment by arodic** [comment]
Getting the code through Skype does not work. Clicking the link opens Skype with interface to create a new empty group. Is this some sort of puzzle we have to solve to get the code?

**Comment by subhasisbanik** [comment]
Any update on this?

**Comment by zaq1tomo** [comment]
@stephantual @cubedro

**Comment by jamiew** [comment]
If GitHub had messaging I'd send it to you. Could hit me up on Twitter @jamiew and I can send your way

**Comment by jameschen-epro** [comment]
Where can I get one?

**Comment by tinybike** [comment]
Heads up @cubedro @stephantual et al:

Since this repo is apparently abandoned -- and the Skype channel in which you could originally get the WS_SECRET has also been abandoned, and the only way to get the WS_SECRET is to DM @jamiew on Twitter (??) -- I've forked this repo to https://github.com/tinybike/eth-net-intelligence-api and hardcoded in the WS_SECRET value.

Please ping me (DM @tensorjack on Twitter, or email jack@augur.net) if you guys want me to remove my fork / if for whatever reason you don't want me shouting the WS_SECRET from the rooftops.

**Comment by jonnyhsy** [comment]
@tinybike Hi Jack, how do you get this ws_secret in your forked repo? I'm guessing I should not reuse your ws_secret otherwise some uninteresting conflicts would happen right?

**Comment by thomasyuan** [comment]
As @tinybike said, this repo is abandoned, because the functionality of this repo is already part of the ethereum (geth), so you needn’t this repo at all.

Run geth with this parameter:
‘’’
--ethstats value                  Reporting URL of a ethstats service (nodename:secret@host:port)
‘’’

**Comment by jamiew** [comment]
One still requires the secret in order to report to ethstats.net — maybe we can update that app to explain better?

**Comment by tinybike** [comment]
@jonnyhsy AFAIK it's fine to re-use the secret!
